# Generated by Django 4.2.7 on 2023-11-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_data_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='sobrenome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
