# Generated by Django 4.2.7 on 2023-12-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0007_pessoa_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='foto',
        ),
    ]
